### ISSUE TITLE
'WootricSDK/WootricSDK.h' file not found

### ISSUE THREAD

**Issue by renan5by5** [Wootric/react-native-wootric#3]
I'm trying to add the SDK to react-native, I run the commands:
$ yarn add https://github.com/Wootric/react-native-wootric --save
$ react-native link react-native-wootric
When I'm going to build the application, the error below
RNWootric.m:1:9: fatal error: 'WootricSDK/WootricSDK.h' file not found
#import <WootricSDK/WootricSDK.h>
^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
** BUILD FAILED **

please, could you help me?

**Comment by asjustis** [comment]
hey @renan5by5 did you do this step provided here? https://github.com/Wootric/react-native-wootric#ios-only-additional-steps-for-ios

I also had the same problem and this helped. It builds and runs, but crashes on startup though.

```dyld: Library not loaded: @rpath/WootricSDK.framework/WootricSDK
  Referenced from: /var/containers/Bundle/Application/MyApp.app/MyApp
  Reason: image not found
(lldb) ```

**Comment by asjustis** [comment]
@diegoserranoa @ambarwootric can you guys check this? The updated plugin fixes Android issues, but this one for iOS is still happening. Is it possible to integrate WootricSDK into the plugin, so that it works straight from npm/yarn?

**Comment by diegoserranoa** [comment]
hi @asjustis, let me try this and I'll come back with an update tomorrow, is that ok?

**Comment by asjustis** [comment]
@diegoserranoa that would be amazing. The main issue is that we need to clean node_modules/ dir quite often when switching branches, so anything towards that helps :)

**Comment by gyleg5** [comment]
Agreed that we need the SDK included.  With the new update the iOS package doesn't even compile.  The instructions to manually copy the sdk have been removed so I'm not sure if that's still needed or not, but it also wouldn't matter as we need everything self contained within the module.

**Comment by felipeViana** [comment]
Any updates on this issue?

**Comment by danielbucher** [comment]
I'm having the same issue too. Any updates here?

**Comment by alvaromb** [comment]
What's the actual installation process for iOS? Do we need to manually link the SDK?

**Comment by gyleg5** [comment]
This is still an issue btw, it should probably stay opened.
